openapi: 3.0.0
info:
  title: 'Cal.diy API v2 Api Keys Deprecated: Platform / Webhooks API'
  description: ''
  version: 1.0.0
  contact: {}
servers: []
tags:
- name: 'Deprecated: Platform / Webhooks'
paths:
  /v2/oauth-clients/{clientId}/webhooks:
    post:
      operationId: OAuthClientWebhooksController_createOAuthClientWebhook
      summary: Create a webhook
      description: <Warning>These endpoints are deprecated and will be removed in the future.</Warning>
      parameters:
      - name: x-cal-secret-key
        in: header
        description: OAuth client secret key
        required: true
        schema:
          type: string
      - name: clientId
        required: true
        in: path
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateWebhookInputDto'
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OAuthClientWebhookOutputResponseDto'
      tags:
      - 'Deprecated: Platform / Webhooks'
    get:
      operationId: OAuthClientWebhooksController_getOAuthClientWebhooks
      summary: Get all webhooks
      description: <Warning>These endpoints are deprecated and will be removed in the future.</Warning>
      parameters:
      - name: x-cal-secret-key
        in: header
        description: OAuth client secret key
        required: true
        schema:
          type: string
      - name: clientId
        required: true
        in: path
        schema:
          type: string
      - name: take
        required: false
        in: query
        description: Maximum number of items to return
        schema:
          minimum: 1
          maximum: 250
          default: 250
          example: 25
          type: number
      - name: skip
        required: false
        in: query
        description: Number of items to skip
        schema:
          minimum: 0
          default: 0
          example: 0
          type: number
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OAuthClientWebhooksOutputResponseDto'
      tags:
      - 'Deprecated: Platform / Webhooks'
    delete:
      operationId: OAuthClientWebhooksController_deleteAllOAuthClientWebhooks
      summary: Delete all webhooks
      description: <Warning>These endpoints are deprecated and will be removed in the future.</Warning>
      parameters:
      - name: x-cal-secret-key
        in: header
        description: OAuth client secret key
        required: true
        schema:
          type: string
      - name: clientId
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeleteManyWebhooksOutputResponseDto'
      tags:
      - 'Deprecated: Platform / Webhooks'
  /v2/oauth-clients/{clientId}/webhooks/{webhookId}:
    patch:
      operationId: OAuthClientWebhooksController_updateOAuthClientWebhook
      summary: Update a webhook
      description: <Warning>These endpoints are deprecated and will be removed in the future.</Warning>
      parameters:
      - name: x-cal-secret-key
        in: header
        description: OAuth client secret key
        required: true
        schema:
          type: string
      - name: webhookId
        required: true
        in: path
        schema:
          type: string
      - name: clientId
        required: true
        in: path
        schema:
          type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateWebhookInputDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OAuthClientWebhookOutputResponseDto'
      tags:
      - 'Deprecated: Platform / Webhooks'
    get:
      operationId: OAuthClientWebhooksController_getOAuthClientWebhook
      summary: Get a webhook
      description: <Warning>These endpoints are deprecated and will be removed in the future.</Warning>
      parameters:
      - name: x-cal-secret-key
        in: header
        description: OAuth client secret key
        required: true
        schema:
          type: string
      - name: webhookId
        required: true
        in: path
        schema:
          type: string
      - name: clientId
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OAuthClientWebhookOutputResponseDto'
      tags:
      - 'Deprecated: Platform / Webhooks'
    delete:
      operationId: OAuthClientWebhooksController_deleteOAuthClientWebhook
      summary: Delete a webhook
      description: <Warning>These endpoints are deprecated and will be removed in the future.</Warning>
      parameters:
      - name: x-cal-secret-key
        in: header
        description: OAuth client secret key
        required: true
        schema:
          type: string
      - name: webhookId
        required: true
        in: path
        schema:
          type: string
      - name: clientId
        required: true
        in: path
        schema:
          type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OAuthClientWebhookOutputResponseDto'
      tags:
      - 'Deprecated: Platform / Webhooks'
components:
  schemas:
    OAuthClientWebhookOutputResponseDto:
      type: object
      properties:
        status:
          type: string
          example: success
          enum:
          - success
          - error
        data:
          $ref: '#/components/schemas/OAuthClientWebhookOutputDto'
      required:
      - status
      - data
    UpdateWebhookInputDto:
      type: object
      properties:
        payloadTemplate:
          type: string
          description: The template of the payload that will be sent to the subscriberUrl, check cal.com/docs/core-features/webhooks for more information
          example: '{"content":"A new event has been scheduled","type":"{{type}}","name":"{{title}}","organizer":"{{organizer.name}}","booker":"{{attendees.0.name}}"}'
        active:
          type: boolean
        subscriberUrl:
          type: string
        triggers:
          type: array
          example:
          - BOOKING_CREATED
          - BOOKING_RESCHEDULED
          - BOOKING_CANCELLED
          - BOOKING_CONFIRMED
          - BOOKING_REJECTED
          - BOOKING_COMPLETED
          - BOOKING_NO_SHOW
          - BOOKING_REOPENED
          items:
            type: string
            enum:
            - BOOKING_CREATED
            - BOOKING_PAYMENT_INITIATED
            - BOOKING_PAID
            - BOOKING_RESCHEDULED
            - BOOKING_REQUESTED
            - BOOKING_CANCELLED
            - BOOKING_REJECTED
            - BOOKING_NO_SHOW_UPDATED
            - FORM_SUBMITTED
            - MEETING_ENDED
            - MEETING_STARTED
            - RECORDING_READY
            - INSTANT_MEETING
            - RECORDING_TRANSCRIPTION_GENERATED
            - OOO_CREATED
            - AFTER_HOSTS_CAL_VIDEO_NO_SHOW
            - AFTER_GUESTS_CAL_VIDEO_NO_SHOW
            - FORM_SUBMITTED_NO_EVENT
            - DELEGATION_CREDENTIAL_ERROR
            - WRONG_ASSIGNMENT_REPORT
        secret:
          type: string
        version:
          type: string
          description: The version of the webhook
          example: '2021-10-20'
          enum:
          - '2021-10-20'
    CreateWebhookInputDto:
      type: object
      properties:
        payloadTemplate:
          type: string
          description: The template of the payload that will be sent to the subscriberUrl, check cal.com/docs/core-features/webhooks for more information
          example: '{"content":"A new event has been scheduled","type":"{{type}}","name":"{{title}}","organizer":"{{organizer.name}}","booker":"{{attendees.0.name}}"}'
        active:
          type: boolean
        subscriberUrl:
          type: string
        triggers:
          type: array
          example:
          - BOOKING_CREATED
          - BOOKING_RESCHEDULED
          - BOOKING_CANCELLED
          - BOOKING_CONFIRMED
          - BOOKING_REJECTED
          - BOOKING_COMPLETED
          - BOOKING_NO_SHOW
          - BOOKING_REOPENED
          items:
            type: string
            enum:
            - BOOKING_CREATED
            - BOOKING_PAYMENT_INITIATED
            - BOOKING_PAID
            - BOOKING_RESCHEDULED
            - BOOKING_REQUESTED
            - BOOKING_CANCELLED
            - BOOKING_REJECTED
            - BOOKING_NO_SHOW_UPDATED
            - FORM_SUBMITTED
            - MEETING_ENDED
            - MEETING_STARTED
            - RECORDING_READY
            - INSTANT_MEETING
            - RECORDING_TRANSCRIPTION_GENERATED
            - OOO_CREATED
            - AFTER_HOSTS_CAL_VIDEO_NO_SHOW
            - AFTER_GUESTS_CAL_VIDEO_NO_SHOW
            - FORM_SUBMITTED_NO_EVENT
            - DELEGATION_CREDENTIAL_ERROR
            - WRONG_ASSIGNMENT_REPORT
        secret:
          type: string
        version:
          type: string
          description: The version of the webhook
          example: '2021-10-20'
          enum:
          - '2021-10-20'
      required:
      - active
      - subscriberUrl
      - triggers
    DeleteManyWebhooksOutputResponseDto:
      type: object
      properties:
        status:
          type: string
          example: success
          enum:
          - success
          - error
        data:
          type: string
      required:
      - status
      - data
    OAuthClientWebhookOutputDto:
      type: object
      properties:
        payloadTemplate:
          type: string
          description: The template of the payload that will be sent to the subscriberUrl, check cal.com/docs/core-features/webhooks for more information
          example: '{"content":"A new event has been scheduled","type":"{{type}}","name":"{{title}}","organizer":"{{organizer.name}}","booker":"{{attendees.0.name}}"}'
        triggers:
          type: array
          items:
            type: string
            enum:
            - BOOKING_CREATED
            - BOOKING_PAYMENT_INITIATED
            - BOOKING_PAID
            - BOOKING_RESCHEDULED
            - BOOKING_REQUESTED
            - BOOKING_CANCELLED
            - BOOKING_REJECTED
            - BOOKING_NO_SHOW_UPDATED
            - FORM_SUBMITTED
            - MEETING_ENDED
            - MEETING_STARTED
            - RECORDING_READY
            - INSTANT_MEETING
            - RECORDING_TRANSCRIPTION_GENERATED
            - OOO_CREATED
            - AFTER_HOSTS_CAL_VIDEO_NO_SHOW
            - AFTER_GUESTS_CAL_VIDEO_NO_SHOW
            - FORM_SUBMITTED_NO_EVENT
            - DELEGATION_CREDENTIAL_ERROR
            - WRONG_ASSIGNMENT_REPORT
        oAuthClientId:
          type: string
        id:
          type: number
        subscriberUrl:
          type: string
        active:
          type: boolean
        secret:
          type: string
      required:
      - payloadTemplate
      - triggers
      - oAuthClientId
      - id
      - subscriberUrl
      - active
    OAuthClientWebhooksOutputResponseDto:
      type: object
      properties:
        status:
          type: string
          example: success
          enum:
          - success
          - error
        data:
          type: array
          items:
            $ref: '#/components/schemas/OAuthClientWebhookOutputDto'
      required:
      - status
      - data
